[ss-levels]
levels = [
    "Persuade the baby",
    "Persuade the puncher",
    "Persuasion",
    "Persuasion",
    "Persuasion",
    "1m gun, no intel",
    "1m gun, intel",
    "2m gun, no intel",
    "1 armor vs 2m, no intel",
    "1 armor vs 1a2m, no intel",
    "2v2, no armor",
    "2v2, armor",
    "2v2 with axe",
    "decoy baby",
    "introduce: property (1v1p)",
    "introduce: freebies (0v0f1)",
    "introduce: gathering resources (peaceful)",
    "introduce: food",
    "2v2f1",
    "1v1f2",
    "2v2pf1",
    "1v1p",
    "introduce: conservationist 1",
    "craftable: armor enhancement kit",
    "craftable: wood and stone armor",
    "introduce: smelting, iron armor",
    "introduce: deep mine, cosmium armor, diamond armor",
    "2v3",
    "gathering",
    "boss battle"

]