name: toItch

env:
  itchio_project: user/project-name
  itchio_channel: windows

on: push

jobs:
  exports:
    name: Build, Release, and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      
      - name: Upload to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/stuff
          project: blocks
          channel: html5
        
          api-key: ${{ secrets.ITCH_API_KEY }}
